<?php
/*
use bornfight\wpHelpers\ACFDataProvider;
$acfInstance = ACFDataProvider::getInstance()->setPrefix('autogenerated_-_');
 */
?>

<section class="o-section <?= $modifier_class ?>">
    <div class="o-container">
        <div class="o-section__heading">
            <h2>section heading</h2>
        </div>
        <div class="o-section__content">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi dicta, id numquam odio porro quisquam. Dolores ea fuga, modi natus officiis pariatur totam? Animi, architecto distinctio ducimus ipsam mollitia ut.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam architecto at delectus distinctio earum enim itaque quibusdam sed vitae! Adipisci alias aut, eum ex expedita fugiat inventore molestias neque quam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus adipisci aliquid blanditiis dignissimos distinctio dolores ea earum fugiat ipsa iste labore, minus neque nihil nulla rem saepe vel velit. Laborum.</p>
        </div>
    </div>
</section>
