export const plugins = [
    "lottie-web/build/player/lottie_light",
    "gsap",
    "is_js",
    "swiper",
    "gsap/dist/SplitText",
    "gsap/dist/ScrollTrigger",
    "gsap/dist/ScrollSmoother",
    "three",
    "three/examples/jsm/loaders/DRACOLoader",
    "three/examples/jsm/loaders/GLTFLoader",
    "@bornfight/b-scroll-to",
    "@bornfight/b-scroll-lock",
    "js-cookie",
];
